seed: 42

data:
    output_path: ./best_model/
    train_path: ./data/train_dist_1.csv
    dev_path: ./data/dev_dist_1.csv
    predict_path: ./data/test.csv
    submission_path: ./prediction/

model:
    model_name: kakaobank/kf-deberta-base
    save_total_limit: 5
    save_steps: 1000

train:
    learning_rate: 5e-5
    batch_size: 32
    max_epoch: 3
    warmup_steps: 500
    weight_decay: 0.01
    evaluation_strategy: steps
    eval_steps: 1000
    loss_function: FocalLoss

log:
    logging_dir: ./logs
    logging_steps: 100

wandb_params:
    project: 'dayeon'
    entity: 'dunning-kruger-klue'
    allow_val_change: True
    dataset: 'dist_1'