seed: 42

preprocessing:
    entity_method: tem_punt_question

data:
    output_path: /data/ephemeral/level2-klue-nlp-02/best_model/
    train_path: /data/ephemeral/dataset/train/train_dist_1.csv
    dev_path: /data/ephemeral/dataset/train/dev_dist_1.csv
    predict_path: /data/ephemeral/dataset/test/test_data.csv
    submission_path: /data/ephemeral/level2-klue-nlp-02/prediction/

model:
    model_name: klue/bert-base
    save_total_limit: 5
    save_steps: 1000

train:
    learning_rate: 3e-5
    batch_size: 1
    max_epoch: 3
    warmup_steps: 500
    weight_decay: 0.01
    evaluation_strategy: steps
    eval_steps: 1000
    loss_function: FocalLoss

log:
    logging_dir: ./logs
    logging_steps: 100

wandb_params:
    project: 'minari'
    entity: 'dunning-kruger-klue'
    allow_val_change: True
    dataset: 'dist_1'