program: /data/ephemeral/00_git_file/sweep.py
name: for_metric
entity: dunning-kruger-klue
project: yum
method: grid
metric:
  goal: maximize
  name: eval/micro f1 score

preprocessing:
    entity_method: test1

data:
    output_path: /data/ephemeral/00_git_file/best_model
    train_path: /data/ephemeral/00_git_file/dataset/__train_dist_1.csv
    dev_path: /data/ephemeral/00_git_file/dataset/__dev_dist_1.csv
    predict_path: /data/ephemeral/dataset/test/test_data.csv
    submission_path: /data/ephemeral/00_git_file/prediction

model:
    save_total_limit: 1
    save_steps: 1000

parameters:
  model_name:
    values:
      ['xlm-roberta-large']
  seed:
    values: [42]
  learning_rate:
    values: [1e-5,3e-5,5e-5]
  batch_size:
    values: [48]
  max_epoch:
    values: [3]
  warmup_steps:
    value:
      500
  weight_decay: 
    value: 0.01
  evaluation_strategy:
    value: 'steps'
  eval_steps:
    value: 500
  gamma :
    value : [0, 0.5, 1, 1.5, 2]
  loss_function:
    value: 'FocalLoss'

log:
    logging_dir: ./logs
    logging_steps: 100
