program: sweep.py
name: for_metric
entity: dunning-kruger-klue
project: minari
method: grid
metric:
  goal: maximize
  name: eval/micro f1 score


preprocessing:
    entity_method: tem_punt_question

data:
    output_path: /data/ephemeral/level2-klue-nlp-02/best_model/
    train_path: /data/ephemeral/dataset/train/train_dist_1.csv
    dev_path: /data/ephemeral/dataset/train/dev_dist_1.csv
    predict_path: /data/ephemeral/dataset/test/test_data.csv
    submission_path: /data/ephemeral/level2-klue-nlp-02/prediction/

model:
    save_total_limit: 1
    save_steps: 1000

parameters:
  model_name:
    values:
      ['team-lucid/deberta-v3-xlarge-korean']
  seed:
    values: [42]
  learning_rate:
    value: 3e-5
  batch_size:
    values: [8]
  max_epoch:
    values: [3]
  warmup_steps:
    value:
      500
  weight_decay: 
    values: [0.01,0.1]
  evaluation_strategy:
    value: 'steps'
  eval_steps:
    value: 1000
  gamma :
    values: [0.5,2]
  loss_function:
    value: 'FocalLoss'
  # method:
  #   values: ['tem_punt','tem_punt_question','question_first_tem_punt']

log:
    logging_dir: ./logs
    logging_steps: 100


