program: sweep.py
name: for_metric
entity: dunning-kruger-klue
project: dayeon
method: grid
metric:
  goal: maximize
  name: eval/micro f1 score


preprocessing:
    entity_method: test2

data:
    output_path: ./best_model/
    train_path: ./data/train_dist_3.csv
    dev_path: ./data/dev_dist_3.csv
    predict_path: ./data/test.csv
    submission_path: ./prediction/

model:
    save_total_limit: 1
    save_steps: 1000

parameters:
  model_name:
    values:
      ['kakaobank/kf-deberta-base']
  seed:
    values: [42]
  learning_rate:
    values: [5e-5]
  batch_size:
    values: [32]
  max_epoch:
    values: [3]
  warmup_steps:
    value:
      500
  weight_decay: 
    values: [0, 0.1, 0.01, 0.001, 0.0001, 0.00001]
  evaluation_strategy:
    value: 'steps'
  eval_steps:
    value: 1000
  loss_function:
    value: 'FocalLoss'

log:
    logging_dir: ./logs
    logging_steps: 100

