program: sweep.py
name: for_metric
entity: dunning-kruger-klue
project: donghyeon
method: grid
metric:
  goal: maximize
  name: eval/micro f1 score


data:
    output_path: ./best_model/
    train_path: ./data/train_dist_1.csv
    dev_path: ./data/dev_dist_1.csv
    predict_path: ./data/test.csv
    submission_path: ./prediction/

model:
    save_total_limit: 1
    save_steps: 1000

parameters:
  model_name:
    values:
      ['klue/bert-base','monologg/koelectra-base-v3-discriminator']
  seed:
    values: [42]
  learning_rate:
    values: [1e-5]
  batch_size:
    values: [32]
  max_epoch:
    values: [2]
  warmup_steps:
    value:
      500
  weight_decay: 
    value: 0.01
  evaluation_strategy:
    value: 'steps'
  eval_steps:
    value: 1000
  loss_function:
    value: 'CE'

log:
    logging_dir: ./logs
    logging_steps: 100

